ALTER TABLE notes ADD COLUMN IF NOT EXISTS share_id UUID UNIQUE;
ALTER TABLE notes ADD COLUMN IF NOT EXISTS is_public BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_notes_share_id ON notes(share_id) WHERE share_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS user_stats (
  user_id VARCHAR(20) PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  ai_requests INT NOT NULL DEFAULT 0
);
